packaging_format = 2

id = "traggo"
name = "Traggo"
description.en = "Tag-based time tracking tool"
description.fr = "Outil de suivi du temps basé sur des étiquettes"

version = "0.7.0~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://traggo.net"
admindoc = "https://traggo.net/config/"
code = "https://github.com/traggo/server"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/traggo/server/releases/download/v0.7.0/traggo_0.7.0_linux_arm64.tar.gz"
        arm64.sha256 = "f2073690cde67018ac40c40eb2c6b3c6867d9fcb19b9dff2d84598a90e10548d"
        amd64.url = "https://github.com/traggo/server/releases/download/v0.7.0/traggo_0.7.0_linux_amd64.tar.gz"
        amd64.sha256 = "40170529438c9dcb4bee6ce766351a949057de9f12ea86e8a6b6f8ec86999c3b"
        armhf.url = "https://github.com/traggo/server/releases/download/v0.7.0/traggo_0.7.0_linux_armv7.tar.gz"
        armhf.sha256 = "4e1550de67f988eb3036b9d11bd578a34141146cabdd3ed3db48e55f4b4ce49d"
        i386.url = "https://github.com/traggo/server/releases/download/v0.7.0/traggo_0.7.0_linux_i386.tar.gz"
        i386.sha256 = "c3f8f34e8cbecf25e802e7a7d09cdd0e4a52160a97b7d057081983199688f1dd"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "^traggo_.*_linux_arm64.tar.gz$"
        autoupdate.asset.amd64 = "^traggo_.*_linux_amd64.tar.gz$"
        autoupdate.asset.armhf = "^traggo_.*_linux_armv7.tar.gz$"
        autoupdate.asset.i386 = "^traggo_.*_linux_i386.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "sqlite3"
