packaging_format = 2

id = "traggo"
name = "Traggo"
description.en = "Tag-based time tracking tool"
description.fr = "Outil de suivi du temps basé sur des étiquettes"

version = "0.8.3~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://traggo.net"
admindoc = "https://traggo.net/config/"
code = "https://github.com/traggo/server"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/traggo/server/releases/download/v0.8.3/traggo_0.8.3_linux_arm64.tar.gz"
        arm64.sha256 = "cc44e61a99b7741cc8c4820f695ce52d1af437e82948e8ab2832b56388990f70"
        amd64.url = "https://github.com/traggo/server/releases/download/v0.8.3/traggo_0.8.3_linux_amd64.tar.gz"
        amd64.sha256 = "c14012c5d4975c23e8214770bba02a106de7fa8fcf1d10c7a127ebec30536639"
        armhf.url = "https://github.com/traggo/server/releases/download/v0.8.3/traggo_0.8.3_linux_armv7.tar.gz"
        armhf.sha256 = "454e2235c268cc4d31de1a27a8430db41d5f1998375b8539353393e0f26e3fa0"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "^traggo_.*_linux_arm64.tar.gz$"
        autoupdate.asset.amd64 = "^traggo_.*_linux_amd64.tar.gz$"
        autoupdate.asset.armhf = "^traggo_.*_linux_armv7.tar.gz$"


    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "sqlite3"
