packaging_format = 2

id = "traggo"
name = "Traggo"
description.en = "Tag-based time tracking tool"
description.fr = "Outil de suivi du temps basé sur des étiquettes"

version = "0.4.5~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://traggo.net"
admindoc = "https://traggo.net/config/"
code = "https://github.com/traggo/server"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/traggo/server/releases/download/v0.4.5/traggo_0.4.5_linux_arm64.tar.gz"
        arm64.sha256 = "842238c8ed530ec56e13932c80f8eb6597faca7d8688bca92157a0b833061f40"
        amd64.url = "https://github.com/traggo/server/releases/download/v0.4.5/traggo_0.4.5_linux_amd64.tar.gz"
        amd64.sha256 = "09e14cdc7085b2cfabd608977e60be2d45b4bb248767c03973a02c4626dda693"
        armhf.url = "https://github.com/traggo/server/releases/download/v0.4.5/traggo_0.4.5_linux_armv7.tar.gz"
        armhf.sha256 = "2f657eccdd608da7d1d250218e6961a2cc1284014ca38639205d9aaf04f4757f"
        i386.url = "https://github.com/traggo/server/releases/download/v0.4.5/traggo_0.4.5_linux_i386.tar.gz"
        i386.sha256 = "d2224072c87bf6b01ef967cd94127926966fde239d682bb67d1d8545d87737d3"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "^traggo_.*_linux_arm64.tar.gz$"
        autoupdate.asset.amd64 = "^traggo_.*_linux_amd64.tar.gz$"
        autoupdate.asset.armhf = "^traggo_.*_linux_armv7.tar.gz$"
        autoupdate.asset.i386 = "^traggo_.*_linux_i386.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "sqlite3"
