packaging_format = 2

id = "traggo"
name = "Traggo"
description.en = "Tag-based time tracking tool"
description.fr = "Outil de suivi du temps basé sur des étiquettes"

version = "0.4.3~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://traggo.net"
admindoc = "https://traggo.net/config/"
code = "https://github.com/traggo/server"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/traggo/server/releases/download/v0.4.3/traggo_0.4.3_linux_arm64.tar.gz"
        arm64.sha256 = "004c35548ccade0fd2ecefb6c199718ecd1d7e5071dab709de155bbb17f049d7"
        amd64.url = "https://github.com/traggo/server/releases/download/v0.4.3/traggo_0.4.3_linux_amd64.tar.gz"
        amd64.sha256 = "bf28626599a038cdf6dac4533425fed2ff2197ff6a21062d3ade1ad795c7b79f"
        armhf.url = "https://github.com/traggo/server/releases/download/v0.4.3/traggo_0.4.3_linux_armv7.tar.gz"
        armhf.sha256 = "2f854f2fd9b055500f33c1d8b484104ff1520c5dbccff0292f0421514570f4f4"
        i386.url = "https://github.com/traggo/server/releases/download/v0.4.3/traggo_0.4.3_linux_i386.tar.gz"
        i386.sha256 = "4fd2b70268aa552fb21b07bcfef60f21c0bf0282f2d58c8387cb0b2c0f496d3e"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "^traggo_.*_linux_arm64.tar.gz$"
        autoupdate.asset.amd64 = "^traggo_.*_linux_amd64.tar.gz$"
        autoupdate.asset.armhf = "^traggo_.*_linux_armv7.tar.gz$"
        autoupdate.asset.i386 = "^traggo_.*_linux_i386.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "sqlite3"
