packaging_format = 2

id = "traggo"
name = "Traggo"
description.en = "Self-hosted tag-based time tracking"
description.fr = "Outil de suivi du temps auto-hébergé"

version = "0.3.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://traggo.net"
admindoc = "https://traggo.net/config/"
code = "https://github.com/traggo/server"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.0.9"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "password"

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/traggo/server/releases/download/v0.3.0/traggo-server-0.3.0-linux-arm64.zip"
        arm64.sha256 = "7430f4540d4f4428be71fc6bde1a7665f652b503f40c47b781fda920ed8437fa"
        amd64.url = "https://github.com/traggo/server/releases/download/v0.3.0/traggo-server-0.3.0-linux-amd64.zip"
        amd64.sha256 = "bde681e8aa60327799c2078649d8646e1d3c1c9d35d34430fd52ce04e419106c"
        armhf.url = "https://github.com/traggo/server/releases/download/v0.3.0/traggo-server-0.3.0-linux-arm-7.zip"
        armhf.sha256 = "420a1c7e091fcdea86c9c3ff5aebc294875b9a4db7199739caf85339ba655052"
        i386.url = "https://github.com/traggo/server/releases/download/v0.3.0/traggo-server-0.3.0-linux-386.zip"
        i386.sha256 = "c45aa6db1088b07323b1f076eff728834c531e6e739d86f767ba96972d07b457"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
